import type { User } from './user';

export interface LoginRequest {
  /** Email address or username. */
  identifier: string;
  password: string;
}

export interface AuthTokens {
  access: string;
  refresh: string;
}

export interface LoginResponse extends AuthTokens {
  user: User;
}

/** The username is generated by the backend from the email. */
export interface RegisterRequest {
  full_name: string;
  email: string;
  password: string;
  /** Optional; when sent the backend checks that it matches `password`. */
  password_confirm?: string;
}

export interface RegisterResponse {
  message: string;
  user: User;
}

export interface ChangePasswordRequest {
  current_password: string;
  new_password: string;
  new_password_confirm: string;
}
